[package]
name = "bevy-inspector-egui-demo"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
bevy-inspector-egui = "0.14"
bevy = { version = "0.9", default-features = false, features = ["bevy_winit", "render"] }

[profile.release]
lto = "thin"
opt-level = 's'
